version: '3.8'

services:
  app:
    build: .
    image: nextjsapp:latest
    environment:
      - DATABASE_URL=postgresql://postgres:admin1@postgres_db:5432/test_db
    ports:
      - '3000:3000'
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: unless-stopped

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      DATABASE_URL: postgresql://postgres:admin1@postgres_db:5432/test_db
    depends_on:
      - postgres_db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:8080
    networks:
      - db_network

networks:
  db_network:

volumes:
  postgres_data:
  pgadmin-data:
